### ISSUE TITLE
youtube views

### ISSUE THREAD

**Issue by Yurri19** [epctex/traffic-generator#2]
Is it possible to make views for youtube?

**Comment by Yurri19** [comment]
But is it possible for you to make one for youtube?

**Comment by tugkan** [comment]
@Yurri19 Technically, it is possible but we've to check how much time it'll take to make this done. I'll talk with the Product Managers and let them add this to our roadmap. Once the project is ready or once we have a  clear deadline, I'll let you know.

Best.

**Comment by Yurri19** [comment]
Hey, the actor's free trial doesn't work anymore? It's just that I had bought it once and I had tested it before buying it and it seems that it is no longer active

**Comment by tugkan** [comment]
Hey @Yurri19 ! 

The actor has no free trial because of a particular request we've received from Apify. 

Best

**Comment by Yurri19** [comment]
Hi, did you manage to approve the idea of ​​the YouTube view bot?

**Comment by tugkan** [comment]
Hey @Yurri19 !

We just deployed a new version where the actor is able to generate YouTube view counts. It is an experimental feature at the current moment but it is able to still generate.

You can set the `enableYoutube` attribute to `true` on `PAGEVIEW` mode. Please keep in mind that YouTube doesn't count views if they are lower than a specific amount of seconds or percentage. Therefore, for the best experience, we highly suggest you set the `waitOnPage` attribute.

Please let me know if there is anything that I can assist you with,
Best

**Comment by Yurri19** [comment]
Ah, that's great, thanks, but isn't there a free trial to try? My Apify subscription has already ended

**Comment by tugkan** [comment]
Hey @Yurri19 ! Unfortunately, Traffic Generator doesn't come up with a subscription due to a mutual agreement with the Apify Platform. 

Best

**Comment by Yurri19** [comment]
Is there any way I can test the actor?

**Comment by Yurri19** [comment]
I really want to test it

**Comment by tugkan** [comment]
Hey @Yurri19 !

I completely understand your point and totally agree with you. Renting an actor without test is tough.

However, due to the past problems we had in the Apify Platform related to the Traffic Generator, there is no way for this actor to have a trial period in the near future. It is not just our decision but also Apify's. Therefore, it is out of our hands at the current moment.

Thank you for your understanding.
Best

**Comment by tugkan** [comment]
Hey @Yurri19 !

For a short period of time, we decided to enable the Free Trial. It will be for a day for the testing period and you will be able to test the actor within your needs.

These changes will be effective on the 28th of October. This means that the Traffic Generator will have a 1-day trial mode starting from the 28th of October.

Please let me know if you need any further assistance,
Best
